
# policy.1
# Organization section updated with the policies
# Admin policies for Acme set such that either the
# admin of Acme org can take an admin action or the admin from
# Orderer org can take the action.   
# Budget Or admin actions require signatures from both Budget.admin
# and Orderer Org admin

# ORGANIZATIONS
Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/acme.com/msp
    Policies: &OrdererPolicies
      Readers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('OrdererMSP.admin')"

  - &Acme
    Name: Acme
    ID: AcmeMSP
    MSPDir: ./crypto-config/peerOrganizations/acme.com/msp
    Policies: &AcmePolicies
      Readers:
          Type: Signature
          Rule: "OR('AcmeMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('AcmeMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('AcmeMSP.admin', 'OrdererMSP.admin')"
    AnchorPeers:
      - Host: localhost
        Port: 7051

  - &Budget
    Name: Budget
    ID: BudgetMSP
    MSPDir: ./crypto-config/peerOrganizations/budget.com/msp
    Policies: &BudgetPolicies
      Readers:
          Type: Signature
          Rule: "OR('BudgetMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('BudgetMSP.member')"
      Admins:
          Type: Signature
          Rule: "AND('BudgetMSP.admin','OrdererMSP.admin')"
    AnchorPeers:
      - Host: localhost
        Port: 8051

#   ORDERER
Orderer: &OrdererDefaults

  OrdererType: solo

  Addresses:
    - localhost:7050

  # Batch Timeout: The amount of time to wait before creating a batch
  BatchTimeout: 2s

  # Batch Size: Controls the number of messages batched into a block
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Capabilities:


Application: &ApplicationDefaults
 
  Organizations:

  Capabilities:
 

#   CHANNEL
Channel: &ChannelDefaults

  Capabilities:

  
#   PROFILES
Profiles:

  AirlineOrdererGenesis:
      <<: *ChannelDefaults
      Orderer:
          <<: *OrdererDefaults
          Organizations:
              - <<: *Orderer


      Application:
            <<: *ApplicationDefaults

            Organizations:
                - <<: *Acme
                - <<: *Budget
                 

      Consortiums:

        AirlineConsortium:
            
            Organizations:
                  - <<: *Acme
                  - <<: *Budget
                                
                  
  AirlineChannel:
    <<: *ChannelDefaults
    Consortium: AirlineConsortium
        
    Application:
        <<: *ApplicationDefaults
        
        Organizations:
            - <<: *Acme
            - <<: *Budget
        


  