# config.1
# Added an additional bootstrap identity - user

#############################################################################
#   This is a configuration file for the fabric-ca-server command.
#############################################################################

# Version of config file
version: 1.2.1-snapshot-3bcdbb2

# Server's listening port (default: 7054)
port: 7054

# Enables debug logging (default: false)
debug: false

# Size limit of an acceptable CRL in bytes (default: 512000)
crlsizelimit: 512000
#############################################################################
#  The CA section contains information related to the Certificate Authority
#############################################################################
ca:
  # Unique Name (across the network) of this CA
  name: acme-ca
  # Key file (is only used to import a private key into BCCSP)
  keyfile:
  # Certificate file (default: ca-cert.pem)
  certfile:
  # Chain file - contains certificates that may be trusted
  chainfile:
#############################################################################
# Affiliations are hierarchical in nature. 
#############################################################################
affiliations:
   acme:
      - logistics
      - accounting
   orderer:
      - support
#############################################################################
#  Used for ID registry setup
#############################################################################
registry:
  # Default - Maximum number of times a password/secret can be reused for enrollment
  maxenrollments: -1

  # Contains identity information which is used when LDAP is disabled
  identities:
      - name: admin
        pass: adminpw
        type: client
        affiliation: ""
        attrs:
            hf.Registrar.Roles: "*"
            hf.Registrar.DelegateRoles: "*"
            hf.Revoker: true
            hf.IntermediateCA: true
            hf.GenCRL: true
            hf.Registrar.Attributes: "*"
            hf.AffiliationMgr: true
      # Added this i config.1
      - name: user
        pass: userpw
        type: user
        affiliation: "acme"
        maxenrollments: 2
        attrs:
            # Should not be able to revoke 
            hf.Revoker: false
            # Should not be able to setup ICA
            hf.IntermediateCA: false
            # Should not be able to manage CRL
            hf.GenCRL: false
            # Should not be able to manage affiliation
            hf.AffiliationMgr: false
            
###########################################################################
#  Certificate Signing Request (CSR) section.
#  This controls the creation of the root CA certificate.
###########################################################################
csr:
   cn: Acme-CA
   names:
      - C: US
        ST: "New York"
        L: Newark
        O: Acme
        OU: B2B
   hosts:
     - acme.com
     - localhost
   ca:
      expiry: 131400h
      
#      pathlength: 1
#############################################################################
#  Signing section - default config used for signing ECerts
#  Profile-ca used for signing ICA certs, Profile-tls used for sign TLS certs
#############################################################################
signing:
    default:
      usage:
        - digital signature
      expiry: 8760h
    profiles:
      ca:
         usage:
           - cert sign
           - crl sign
         expiry: 43800h
         caconstraint:
           isca: true
           maxpathlen: 0
      tls:
         usage:
            - signing
            - key encipherment
            - server auth
            - client auth
            - key agreement
         expiry: 8760h
#############################################################################
#  TLS section for the server's listening port
#############################################################################
tls:
  # Enable TLS (default: false)
  enabled: false
  # TLS for the server's listening port
  certfile:
  keyfile:
  clientauth:
    type: noclientcert
    certfiles:



#############################################################################
# This section contains configuration options that are used
# during gencrl request processing.
#############################################################################
crl:
  # Specifies expiration for the generated CRL. 
  expiry: 24h



#############################################################################
#  Database section - Supported types are: "sqlite3", "postgres", and "mysql".
#############################################################################
db:
  type: sqlite3
  datasource: fabric-ca-server.db
  tls:
      enabled: false
      certfiles:
      client:
        certfile:
        keyfile:

#############################################################################
#  LDAP section
#############################################################################
ldap:
   # Enables/disables LDAP client, if true Registry section ignored
   enabled: false
   # The URL of the LDAP server
   url: ldap://<adminDN>:<adminPassword>@<host>:<port>/<base>
   # TLS configuration for the client connection to the LDAP server
   tls:
      certfiles:
      client:
         certfile:
         keyfile:
   # Attribute related configuration for mapping from LDAP entries to Fabric CA attributes
   attribute:
      # 'names' is an array of strings containing the LDAP attribute names which are
      # requested from the LDAP server for an LDAP identity's entry
      names: ['uid','member']
      # Config for converting LDAP attributes to CA/Fabric attributes
      converters:
         - name:
           value:
      # The 'maps' section contains named maps which may be referenced by the 'map'
      # function in the 'converters' section to map LDAP responses to arbitrary values.
      maps:
         groups:
            - name:
              value:


#############################################################################
# Multi CA section - setup multiple CA in a single Server process
#############################################################################

cacount:

cafiles:

#############################################################################
# Intermediate CA section - for setting up an ICA
#############################################################################
intermediate:
  parentserver:
    url:
    caname:

  enrollment:
    hosts:
    profile:
    label:

  tls:
    certfiles:
    client:
      certfile:
      keyfile:

#############################################################################
# BCCSP (BlockChain Crypto Service Provider) section is used to select which
# crypto library implementation to use
#############################################################################
bccsp:
    default: SW
    sw:
        hash: SHA2
        security: 256
        filekeystore:
            # The directory used for the software file-based keystore
            keystore: msp/keystore